# Generated by Django 3.0.7 on 2020-06-24 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_section_title', models.CharField(max_length=128)),
                ('company_section_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 762213))),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 760219))),
            ],
        ),
        migrations.CreateModel(
            name='Maalem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maalem_title', models.CharField(max_length=50)),
                ('maalem_descriptions', models.TextField()),
                ('maalem_principal_image', models.ImageField(upload_to='maalem/principal')),
                ('maalem_loaction', models.CharField(default='haret hreik', max_length=128)),
                ('maalem_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 761214))),
            ],
        ),
        migrations.CreateModel(
            name='NewsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128)),
                ('news_description', models.TextField()),
                ('news_principale_image', models.ImageField(upload_to='News/')),
                ('news_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 757228))),
            ],
        ),
        migrations.CreateModel(
            name='NewsDecisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128)),
                ('news_description', models.TextField()),
                ('news_principale_image', models.ImageField(upload_to='News/')),
                ('news_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 756234))),
            ],
        ),
        migrations.CreateModel(
            name='NewsProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128)),
                ('news_description', models.TextField()),
                ('news_principale_image', models.ImageField(upload_to='News/')),
                ('news_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 758231))),
                ('news_projects_finish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('Question_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Question_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Question_title', models.CharField(blank=True, max_length=128, null=True)),
                ('Question_text', models.TextField(blank=True, null=True)),
                ('Question_principal_image', models.ImageField(blank=True, null=True, upload_to='Question/principal')),
                ('Question_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 19, 11, 759222), null=True)),
                ('Question_show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_value_realty_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rental_value_block_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rental_vlaue_section', models.CharField(blank=True, max_length=10, null=True)),
                ('rental_value_additional_code', models.CharField(blank=True, max_length=100, null=True)),
                ('rental_value_total', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_title', models.CharField(max_length=200)),
                ('transactions_descriptions', models.TextField(blank=True, null=True)),
                ('transactions_file', models.FileField(upload_to='transactions/')),
                ('response_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 760219))),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_image', models.ImageField(blank=True, null=True, upload_to='Response/secondary/')),
                ('response_file', models.FileField(blank=True, null=True, upload_to='Response/File/')),
                ('response_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='website.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_title', models.CharField(blank=True, max_length=128, null=True)),
                ('response_description', models.TextField()),
                ('response_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 759222))),
                ('response_principal_image', models.ImageField(blank=True, null=True, upload_to='Response/pricipal')),
                ('response_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='website.Question')),
            ],
        ),
        migrations.CreateModel(
            name='RentalValueBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_value_bill_date', models.DateField()),
                ('rental_value_bill_value', models.CharField(max_length=20)),
                ('rental_value_bill_rental_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='website.RentalValue')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='website.QuestionType'),
        ),
        migrations.CreateModel(
            name='NewsFileProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_file', models.FileField(blank=True, null=True, upload_to='News/File/')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='News/Image/')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectfile', to='website.NewsProjects')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFileDecisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_file', models.FileField(blank=True, null=True, upload_to='News/File/')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='News/Image/')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisionfile', to='website.NewsDecisions')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFileActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_file', models.FileField(blank=True, null=True, upload_to='News/File/')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='News/Image/')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityfile', to='website.NewsActivity')),
            ],
        ),
        migrations.CreateModel(
            name='MaalemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maalem_image_image', models.ImageField(upload_to='maalem/secondary/')),
                ('maalem_image_maalem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='website.Maalem')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type_title', models.CharField(max_length=128)),
                ('company_type_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 762213))),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='website.CompanySection')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=128)),
                ('company_location', models.CharField(default='حارة حريك', max_length=200)),
                ('company_tell', models.CharField(blank=True, max_length=128, null=True)),
                ('company_date', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 11, 762213))),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='website.CompanyType')),
            ],
        ),
    ]
