# Generated by Django 3.0.7 on 2020-06-24 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 255194)),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='company_section_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 255194)),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='company_type_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 255194)),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 253200)),
        ),
        migrations.AlterField(
            model_name='maalem',
            name='maalem_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 254197)),
        ),
        migrations.AlterField(
            model_name='newsactivity',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 250208)),
        ),
        migrations.AlterField(
            model_name='newsdecisions',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 249210)),
        ),
        migrations.AlterField(
            model_name='newsprojects',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 251205)),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 19, 37, 252202), null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 252202)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='response_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 19, 37, 253200)),
        ),
    ]
