# Generated by Django 3.0.7 on 2020-06-24 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200624_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 815013), null=True),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='company_section_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 815013), null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='company_type_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 815013), null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 23, 20, 813021)),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maalem',
            name='maalem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 814015), null=True),
        ),
        migrations.AlterField(
            model_name='newsactivity',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 23, 20, 810026)),
        ),
        migrations.AlterField(
            model_name='newsdecisions',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 23, 20, 809029)),
        ),
        migrations.AlterField(
            model_name='newsprojects',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 17, 23, 20, 811030)),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 812021), null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 812021), null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='response_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 17, 23, 20, 813021), null=True),
        ),
    ]
