# Generated by Django 3.0.7 on 2020-07-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200703_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='specialcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
